name: Pull request
on:
  pull_request:
  issue_comment:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
        name: Install
      - run: npm run all
        name: Compile Typescript, run tests and package
  run-self:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: get_changed
        with:
          github-token: ${{ github.token }}
      - name: Echo
        run: echo ${{ steps.get_changed.outputs.changed }}
